name: "Tag and release terraform module"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  tag-and-release:
    uses: dsb-norge/github-actions-terraform/.github/workflows/terraform-module-release.yaml@v0
    secrets: inherit
